name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      # Tải xuống NSSM
      - name: Download NSSM
        run: Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/nssm.exe -OutFile nssm.exe

      # Sao chép NSSM & Ngrok vào thư mục Windows
      - name: Copy NSSM & Ngrok to Windows Directory.
        run:
          copy nssm.exe C:\Windows\System32

      # Xác thực với ngrok
      - name: Authenticate with ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # Cài đặt ngrok
      - name: Install ngrok
        run: |
          # Tạo thư mục .ngrok2 trong thư mục Users\runneradmin
          New-Item -Path "C:\Users\runneradmin\.ngrok2" -ItemType Directory -Force
          # Thay đổi thư mục làm việc sang thư mục .ngrok2
          $ngrokDir = "C:\Users\runneradmin\.ngrok2"
          Set-Location $ngrokDir

          # Tạo file ngrok.yml nếu chưa tồn tại và thêm các dòng cấu hình
          $ngrokYmlPath = Join-Path $ngrokDir -ChildPath "ngrok.yml"
          if (-not (Test-Path $ngrokYmlPath)) {
            New-Item -Path $ngrokYmlPath -ItemType File -Force
          }

          $content = @"
          region: ap
          tunnels:
            default:
              proto: tcp
              addr: 3389
          "@
          Add-Content -Path $ngrokYmlPath -Value $content

      # Kích hoạt Remote Desktop
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      # Tải xuống các tập tin quan trọng
      - name: Download Important Files.
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
          Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/loop.bat -OutFile loop.bat

      # Tạo Tunnel
      - name: Create Tunnel
        run: |
          # Cài đặt NSSM
          nssm install ngrok

          # Khởi động dịch vụ ngrok
          nssm start ngrok

      # Kết nối đến RDP CPU 2 Core - 7GB Ram - 255 SSD.
      - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
        run: cmd /c NGROK-CHECK.bat

      # Hoàn tất! Bạn có thể đóng tab này ngay bây giờ! Thời gian tối đa của VM: 6 giờ.
      - name: All Done! You can close Tab now! Maximum VM time:6h.
        run: cmd /c loop.bat
