name: RDP-VPS

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe  -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/nssm.exe  -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://download854.mediafire.com/e66f0tkcxmegJmYz8elvNsRTcePAD_8dINbK970s0oszkoo8heHZcJCf7vH5ZwI84ewXxQ89zobf0xnmzLVkeUK1bw9zfk24JVfbWpJKdZfbJqYWGkff1ZsjnHHwocY7Ib-1OnrSD7GhReUV5VzofngyMt9tguOtC0Y2-v6lSuh5c-c/9cvpcw3bq536oo9/NGROK-AP.bat  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://download844.mediafire.com/bfotx0hedr1gXqfj-Bx3G0IX08O99oK1vaBtzhf7RE8TIRev-cYbukMJGAKjpf3SuYU21U2DikNNz0VMKcBfvCbF0vbdSZAy8SLXhE1eMr21NsqEbsduU-3_dErsHftWcLvUyN_KJOsK6EHM3Fx_Zc-b9yXLgry7mxhSorNvgSuUy5M/9zo59t32eld99x5/NGROK-CHECK.bat  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/loop.bat  -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
