name: CI

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Copy ngrok
      run: copy ngrok.zip C:\Windows\System32
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Download nssm
      run: Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/nssm.exe  -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run:
        copy nssm.exe C:\Windows\System32
    - name: Authenticate with ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    -name: Mo remote desktop
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/NGROK-AP.bat  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/NGROK-CHECK.bat  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/truongtaoday/taptanh/main/loop.bat  -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
